import type { Metadata } from "next";

import "./globals.css";

import localFont from "next/font/local";

import Direction from "@/provider/Direction";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const iranSansX = localFont({
  src: [
    { path: "/fonts/IRANSansX-Thin.woff", weight: "200", style: "normal" },
    { path: "/fonts/IRANSansX-Light.woff", weight: "300", style: "normal" },
    { path: "/fonts/IRANSansX-Regular.woff", weight: "400", style: "normal" },
    { path: "/fonts/IRANSansX-Medium.woff", weight: "500", style: "normal" },
    { path: "/fonts/IRANSansX-DemiBold.woff", weight: "600", style: "normal" },
    { path: "/fonts/IRANSansX-Bold.woff", weight: "700", style: "normal" },
    { path: "/fonts/IRANSansX-ExtraBold.woff", weight: "900", style: "normal" },
  ],
  display: "swap",
  variable: "--font-iransansx",
  preload: true,
  fallback: ["sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className="no-scroll-bar" dir="rtl">
      <body className={`no-scroll-bar antialiased ${iranSansX.className}`} suppressHydrationWarning>
        <Direction>{children}</Direction>
      </body>
    </html>
  );
}
